server:
  port: 9080
spring:
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
JWT:
  secret: "ThisIStheSecret"
---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/employees
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: dev
test:
  message: "Hellow World"
---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/employees
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: Production
test:
  message: "Hellow World"
---
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/employees
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
    show-sql: true
  config:
    activate:
      on-profile: QA
test:
  message: "Hellow World"